-- MySQL Script generated by MySQL Workbench
-- Tue Feb 17 13:45:55 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema rentora_sphere_v1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rentora_sphere_v1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rentora_sphere_v1` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `rentora_sphere_v1` ;

-- -----------------------------------------------------
-- Table `rentora_sphere_v1`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rentora_sphere_v1`.`users` ;

CREATE TABLE IF NOT EXISTS `rentora_sphere_v1`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` CHAR(36) NOT NULL DEFAULT uuid(),
  `username` VARCHAR(50) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `role` ENUM('user', 'owner', 'sysManager') NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_id` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 35
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `rentora_sphere_v1`.`units`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rentora_sphere_v1`.`units` ;

CREATE TABLE IF NOT EXISTS `rentora_sphere_v1`.`units` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `unit_id` CHAR(36) NOT NULL DEFAULT uuid(),
  `owner_id` INT NULL DEFAULT NULL,
  `title` VARCHAR(255) NOT NULL,
  `price_per_month` DECIMAL(10,2) NOT NULL,
  `status` ENUM('available', 'rented', 'maintenance') NULL DEFAULT 'available',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `unit_id` (`unit_id` ASC) VISIBLE,
  INDEX `fk_unit_owner` (`owner_id` ASC) VISIBLE,
  CONSTRAINT `fk_unit_owner`
    FOREIGN KEY (`owner_id`)
    REFERENCES `rentora_sphere_v1`.`users` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
AUTO_INCREMENT = 72
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `rentora_sphere_v1`.`rent_contracts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rentora_sphere_v1`.`rent_contracts` ;

CREATE TABLE IF NOT EXISTS `rentora_sphere_v1`.`rent_contracts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contract_id` CHAR(36) NOT NULL DEFAULT uuid(),
  `unit_id` INT NOT NULL,
  `tenant_id` INT NOT NULL,
  `owner_id` INT NOT NULL,
  `rent_begin` DATE NOT NULL,
  `rent_end` DATE NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `status` ENUM('active', 'expired', 'cancelled', 'scheduled') NULL DEFAULT 'scheduled',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `contract_id` (`contract_id` ASC) VISIBLE,
  INDEX `fk_contract_unit` (`unit_id` ASC) VISIBLE,
  INDEX `fk_contract_tenant` (`tenant_id` ASC) VISIBLE,
  INDEX `fk_contract_owner` (`owner_id` ASC) VISIBLE,
  CONSTRAINT `fk_contract_owner`
    FOREIGN KEY (`owner_id`)
    REFERENCES `rentora_sphere_v1`.`users` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_contract_tenant`
    FOREIGN KEY (`tenant_id`)
    REFERENCES `rentora_sphere_v1`.`users` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_contract_unit`
    FOREIGN KEY (`unit_id`)
    REFERENCES `rentora_sphere_v1`.`units` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;