-- MySQL Script generated by MySQL Workbench
-- Tue Feb 17 00:46:38 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema rentora_sphere_v1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rentora_sphere_v1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rentora_sphere_v1` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `rentora_sphere_v1` ;

-- -----------------------------------------------------
-- Table `rentora_sphere_v1`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rentora_sphere_v1`.`users` ;

CREATE TABLE IF NOT EXISTS `rentora_sphere_v1`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `role` ENUM('user', 'unitOwner', 'sysManager') NULL DEFAULT 'user',
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `rentora_sphere_v1`.`units`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rentora_sphere_v1`.`units` ;

CREATE TABLE IF NOT EXISTS `rentora_sphere_v1`.`units` (
  `unit_id` INT NOT NULL AUTO_INCREMENT,
  `owner_id` INT NOT NULL,
  `title` VARCHAR(200) NOT NULL,
  `price_per_month` DECIMAL(10,2) NULL DEFAULT NULL,
  `status` VARCHAR(50) NULL DEFAULT 'available',
  PRIMARY KEY (`unit_id`),
  INDEX `fk_unit_owner` (`owner_id` ASC) VISIBLE,
  CONSTRAINT `fk_unit_owner`
    FOREIGN KEY (`owner_id`)
    REFERENCES `rentora_sphere_v1`.`users` (`user_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `rentora_sphere_v1`.`rent_contracts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rentora_sphere_v1`.`rent_contracts` ;

CREATE TABLE IF NOT EXISTS `rentora_sphere_v1`.`rent_contracts` (
  `contract_id` INT NOT NULL AUTO_INCREMENT,
  `unit_id` INT NOT NULL,
  `tenant_id` INT NOT NULL,
  `owner_id` INT NOT NULL,
  `rent_begin` DATE NOT NULL,
  `rent_end` DATE NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `status` ENUM('active', 'expired', 'scheduled') NULL DEFAULT 'scheduled',
  PRIMARY KEY (`contract_id`),
  INDEX `fk_contract_unit` (`unit_id` ASC) VISIBLE,
  INDEX `fk_contract_tenant` (`tenant_id` ASC) VISIBLE,
  INDEX `fk_contract_owner` (`owner_id` ASC) VISIBLE,
  CONSTRAINT `fk_contract_owner`
    FOREIGN KEY (`owner_id`)
    REFERENCES `rentora_sphere_v1`.`users` (`user_id`),
  CONSTRAINT `fk_contract_tenant`
    FOREIGN KEY (`tenant_id`)
    REFERENCES `rentora_sphere_v1`.`users` (`user_id`),
  CONSTRAINT `fk_contract_unit`
    FOREIGN KEY (`unit_id`)
    REFERENCES `rentora_sphere_v1`.`units` (`unit_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
